# Generated by Django 2.2.24 on 2023-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeoCoffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
