# Generated by Django 2.2.24 on 2023-10-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(help_text='Enter Coffee Name', max_length=200)),
                ('coffee_country', models.CharField(help_text='Enter country', max_length=200)),
                ('coffee_type', models.CharField(help_text='Enter the coffee type', max_length=200)),
            ],
        ),
    ]
