# Generated by Django 4.2.6 on 2023-10-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text='Enter Member name', max_length=200)),
                ('member_number', models.CharField(help_text='Enter phone number', max_length=10)),
                ('member_address', models.CharField(help_text='Enter address', max_length=200)),
                ('member_email', models.EmailField(help_text='Enter email', max_length=200)),
            ],
            options={
                'ordering': ['member_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(help_text='Enter coffee name', max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping.member')),
            ],
        ),
    ]
