# Generated by Django 2.2.24 on 2023-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text='Enter Member name', max_length=200)),
                ('member_number', models.CharField(help_text='Enter phone number', max_length=10)),
                ('member_address', models.CharField(help_text='Enter address', max_length=200)),
                ('member_email', models.EmailField(help_text='Enter email', max_length=200)),
            ],
            options={
                'ordering': ['member_name'],
            },
        ),
    ]
